// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACoWFkWp2YgXw7k-ZI9PqsTM31roMM9i0',
    appId: '1:997951838229:web:2e383dbf875296a425161c',
    messagingSenderId: '997951838229',
    projectId: 'portfolioecommerce-app',
    authDomain: 'portfolioecommerce-app.firebaseapp.com',
    storageBucket: 'portfolioecommerce-app.appspot.com',
    measurementId: 'G-2ENDJZ0Q6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgMdmR6Z5CYsy_ICncUapa5ArucopIs8E',
    appId: '1:997951838229:android:01010f47a57ca0e525161c',
    messagingSenderId: '997951838229',
    projectId: 'portfolioecommerce-app',
    storageBucket: 'portfolioecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQAtGSH5X97X1zOEGH-GQCgjw5yjsBRg',
    appId: '1:997951838229:ios:ffc365094d604e3725161c',
    messagingSenderId: '997951838229',
    projectId: 'portfolioecommerce-app',
    storageBucket: 'portfolioecommerce-app.appspot.com',
    androidClientId: '997951838229-87bghoq7sdbjdomph44fpvnq19m6340k.apps.googleusercontent.com',
    iosClientId: '997951838229-4ftlj7f2m2n6f80rmut06ad4cqqgugp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
