import 'package:ecommerce_app/features/shop/Categories/models/categories.model.dart';
import 'package:ecommerce_app/features/shop/product_info/models/brand.model.dart';
import 'package:ecommerce_app/features/shop/product_info/models/product.model.dart';
import 'package:ecommerce_app/features/shop/product_info/models/product_attributes.model.dart';
import 'package:ecommerce_app/features/shop/product_info/models/product_variation.model.dart';

class DummyData {
  DummyData._();
  static List<CategoryModel> dummyCategories = [
    CategoryModel(
      id: '1',
      name: 'Electronics',
      image: 'electronics.jpg',
      isParent: true,
    ),
    CategoryModel(
      id: '2',
      name: 'Clothing',
      image: 'clothing.jpg',
      isParent: true,
    ),
    CategoryModel(
      id: '3',
      name: 'Books',
      image: 'books.jpg',
      isParent: true,
    ),
    CategoryModel(
      id: '4',
      name: 'Smartphones',
      image: 'smartphones.jpg',
      parentId: '1',
      isParent: false,
    ),
    CategoryModel(
      id: '5',
      name: 'Laptops',
      image: 'laptops.jpg',
      parentId: '1',
      isParent: false,
    ),
    CategoryModel(
      id: '6',
      name: 'Men\'s Clothing',
      image: 'mens_clothing.jpg',
      parentId: '2',
      isParent: false,
    ),
    CategoryModel(
      id: '7',
      name: 'Women\'s Clothing',
      image: 'womens_clothing.jpg',
      parentId: '2',
      isParent: false,
    ),
    CategoryModel(
      id: '8',
      name: 'Fiction Books',
      image: 'fiction_books.jpg',
      parentId: '3',
      isParent: false,
    ),
    CategoryModel(
      id: '9',
      name: 'Non-Fiction Books',
      image: 'non_fiction_books.jpg',
      parentId: '3',
      isParent: false,
    ),
    CategoryModel(
      id: '10',
      name: 'Tablets',
      image: 'tablets.jpg',
      parentId: '1',
      isParent: false,
    ),
  ];

  static List<ProductModel> dummyProducts = [
    ProductModel(
      id: "1",
      stock: 150,
      sku: "MT001",
      price: 25.99,
      title: "Men's Casual T-Shirt",
      isFeatured: true,
      salePrice: 19.99,
      thumbnails: [
        "https://example.com/images/mt001_front.jpg",
        "https://example.com/images/mt001_back.jpg"
      ],
      brand: BrandModel(id: "brand1", name: "Brand A"),
      description: "A comfortable and stylish casual t-shirt for men.",
      productType: "variable",
      categoryId: "cat1",
      categories: ["Men", "T-Shirts"],
      tag: "new",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L", "XL"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Blue", "Black"])
      ],
      productVariation: [
        // Red Variations
        ProductVariationModel(
            id: "1-1",
            sku: "MT001-R-S",
            image: "https://example.com/images/mt001_red_s.jpg",
            description: "Red, Small",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "S", "Color": "Red"}),
        ProductVariationModel(
            id: "1-2",
            sku: "MT001-R-M",
            image: "https://example.com/images/mt001_red_m.jpg",
            description: "Red, Medium",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "M", "Color": "Red"}),
        ProductVariationModel(
            id: "1-3",
            sku: "MT001-R-L",
            image: "https://example.com/images/mt001_red_l.jpg",
            description: "Red, Large",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "L", "Color": "Red"}),
        ProductVariationModel(
            id: "1-4",
            sku: "MT001-R-XL",
            image: "https://example.com/images/mt001_red_xl.jpg",
            description: "Red, Extra Large",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "XL", "Color": "Red"}),
        // Blue Variations
        ProductVariationModel(
            id: "1-5",
            sku: "MT001-B-S",
            image: "https://example.com/images/mt001_blue_s.jpg",
            description: "Blue, Small",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        ProductVariationModel(
            id: "1-6",
            sku: "MT001-B-M",
            image: "https://example.com/images/mt001_blue_m.jpg",
            description: "Blue, Medium",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "1-7",
            sku: "MT001-B-L",
            image: "https://example.com/images/mt001_blue_l.jpg",
            description: "Blue, Large",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "L", "Color": "Blue"}),
        ProductVariationModel(
            id: "1-8",
            sku: "MT001-B-XL",
            image: "https://example.com/images/mt001_blue_xl.jpg",
            description: "Blue, Extra Large",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "XL", "Color": "Blue"}),
        // Black Variations
        ProductVariationModel(
            id: "1-9",
            sku: "MT001-BK-S",
            image: "https://example.com/images/mt001_black_s.jpg",
            description: "Black, Small",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "S", "Color": "Black"}),
        ProductVariationModel(
            id: "1-10",
            sku: "MT001-BK-M",
            image: "https://example.com/images/mt001_black_m.jpg",
            description: "Black, Medium",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "1-11",
            sku: "MT001-BK-L",
            image: "https://example.com/images/mt001_black_l.jpg",
            description: "Black, Large",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "L", "Color": "Black"}),
        ProductVariationModel(
            id: "1-12",
            sku: "MT001-BK-XL",
            image: "https://example.com/images/mt001_black_xl.jpg",
            description: "Black, Extra Large",
            price: 25.99,
            salePrice: 19.99,
            quantity: 10,
            attributeValues: {"Size": "XL", "Color": "Black"}),
      ],
    ),
    ProductModel(
      id: "2",
      stock: 100,
      sku: "WD002",
      price: 45.99,
      title: "Women's Summer Dress",
      isFeatured: false,
      salePrice: 39.99,
      thumbnails: [
        "https://example.com/images/wd002_front.jpg",
        "https://example.com/images/wd002_back.jpg"
      ],
      brand: BrandModel(id: "brand2", name: "Brand B"),
      description: "A light and breezy summer dress perfect for warm weather.",
      productType: "variable",
      categoryId: "cat2",
      categories: ["Women", "Dresses"],
      tag: "summer",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["Yellow", "Green"])
      ],
      productVariation: [
        // Yellow Variations
        ProductVariationModel(
            id: "2-1",
            sku: "WD002-Y-S",
            image: "https://example.com/images/wd002_yellow_s.jpg",
            description: "Yellow, Small",
            price: 45.99,
            salePrice: 39.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Yellow"}),
        ProductVariationModel(
            id: "2-2",
            sku: "WD002-Y-M",
            image: "https://example.com/images/wd002_yellow_m.jpg",
            description: "Yellow, Medium",
            price: 45.99,
            salePrice: 39.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Yellow"}),
        ProductVariationModel(
            id: "2-3",
            sku: "WD002-Y-L",
            image: "https://example.com/images/wd002_yellow_l.jpg",
            description: "Yellow, Large",
            price: 45.99,
            salePrice: 39.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Yellow"}),
        // Green Variations
        ProductVariationModel(
            id: "2-4",
            sku: "WD002-G-S",
            image: "https://example.com/images/wd002_green_s.jpg",
            description: "Green, Small",
            price: 45.99,
            salePrice: 39.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Green"}),
        ProductVariationModel(
            id: "2-5",
            sku: "WD002-G-M",
            image: "https://example.com/images/wd002_green_m.jpg",
            description: "Green, Medium",
            price: 45.99,
            salePrice: 39.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Green"}),
        ProductVariationModel(
            id: "2-6",
            sku: "WD002-G-L",
            image: "https://example.com/images/wd002_green_l.jpg",
            description: "Green, Large",
            price: 45.99,
            salePrice: 39.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Green"}),
      ],
    ),
    ProductModel(
      id: "3",
      stock: 80,
      sku: "KH003",
      price: 35.99,
      title: "Kids' Hoodie",
      isFeatured: true,
      salePrice: 29.99,
      thumbnails: [
        "https://example.com/images/kh003_front.jpg",
        "https://example.com/images/kh003_back.jpg"
      ],
      brand: BrandModel(id: "brand3", name: "Brand C"),
      description: "A warm and cozy hoodie for kids.",
      productType: "variable",
      categoryId: "cat3",
      categories: ["Kids", "Hoodies"],
      tag: "sale",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["XS", "S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["Pink", "Grey"])
      ],
      productVariation: [
        // Pink Variations
        ProductVariationModel(
            id: "3-1",
            sku: "KH003-P-XS",
            image: "https://example.com/images/kh003_pink_xs.jpg",
            description: "Pink, Extra Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "XS", "Color": "Pink"}),
        ProductVariationModel(
            id: "3-2",
            sku: "KH003-P-S",
            image: "https://example.com/images/kh003_pink_s.jpg",
            description: "Pink, Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "S", "Color": "Pink"}),
        ProductVariationModel(
            id: "3-3",
            sku: "KH003-P-M",
            image: "https://example.com/images/kh003_pink_m.jpg",
            description: "Pink, Medium",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "M", "Color": "Pink"}),
        ProductVariationModel(
            id: "3-4",
            sku: "KH003-P-L",
            image: "https://example.com/images/kh003_pink_l.jpg",
            description: "Pink, Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "L", "Color": "Pink"}),
        // Grey Variations
        ProductVariationModel(
            id: "3-5",
            sku: "KH003-G-XS",
            image: "https://example.com/images/kh003_grey_xs.jpg",
            description: "Grey, Extra Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "XS", "Color": "Grey"}),
        ProductVariationModel(
            id: "3-6",
            sku: "KH003-G-S",
            image: "https://example.com/images/kh003_grey_s.jpg",
            description: "Grey, Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "S", "Color": "Grey"}),
        ProductVariationModel(
            id: "3-7",
            sku: "KH003-G-M",
            image: "https://example.com/images/kh003_grey_m.jpg",
            description: "Grey, Medium",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "M", "Color": "Grey"}),
        ProductVariationModel(
            id: "3-8",
            sku: "KH003-G-L",
            image: "https://example.com/images/kh003_grey_l.jpg",
            description: "Grey, Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 10,
            attributeValues: {"Size": "L", "Color": "Grey"}),
      ],
    ),
// Men's Clothing
    ProductModel(
      id: "1",
      stock: 150,
      sku: "MT001",
      price: 25.99,
      title: "Men's Casual T-Shirt",
      isFeatured: true,
      salePrice: 19.99,
      thumbnails: [
        "https://example.com/images/mt001_front.jpg",
        "https://example.com/images/mt001_back.jpg"
      ],
      brand: BrandModel(id: "brand1", name: "Brand A"),
      description: "A comfortable and stylish casual t-shirt for men.",
      productType: "variable",
      categoryId: "cat1",
      categories: ["Men", "T-Shirts"],
      tag: "new",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L", "XL"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Blue", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "1-1",
            sku: "MT001-R-S",
            image: "https://example.com/images/mt001_red_s.jpg",
            description: "Red, Small",
            price: 25.99,
            salePrice: 19.99,
            quantity: 50,
            attributeValues: {"Size": "S", "Color": "Red"}),
        ProductVariationModel(
            id: "1-2",
            sku: "MT001-B-M",
            image: "https://example.com/images/mt001_blue_m.jpg",
            description: "Blue, Medium",
            price: 25.99,
            salePrice: 19.99,
            quantity: 50,
            attributeValues: {"Size": "M", "Color": "Blue"}),
      ],
    ),

    // Women's Clothing
    ProductModel(
      id: "2",
      stock: 100,
      sku: "WD002",
      price: 45.99,
      title: "Women's Summer Dress",
      isFeatured: false,
      salePrice: 39.99,
      thumbnails: [
        "https://example.com/images/wd002_front.jpg",
        "https://example.com/images/wd002_back.jpg"
      ],
      brand: BrandModel(id: "brand2", name: "Brand B"),
      description: "A light and breezy summer dress perfect for warm weather.",
      productType: "variable",
      categoryId: "cat2",
      categories: ["Women", "Dresses"],
      tag: "summer",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M"]),
        ProductAttributeModel(name: "Color", values: ["Yellow", "Green"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "2-1",
            sku: "WD002-Y-S",
            image: "https://example.com/images/wd002_yellow_s.jpg",
            description: "Yellow, Small",
            price: 45.99,
            salePrice: 39.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Yellow"}),
        ProductVariationModel(
            id: "2-2",
            sku: "WD002-G-M",
            image: "https://example.com/images/wd002_green_m.jpg",
            description: "Green, Medium",
            price: 45.99,
            salePrice: 39.99,
            quantity: 40,
            attributeValues: {"Size": "M", "Color": "Green"}),
      ],
    ),

    // Kids' Clothing
    ProductModel(
      id: "3",
      stock: 80,
      sku: "KH003",
      price: 35.99,
      title: "Kids' Hoodie",
      isFeatured: true,
      salePrice: 29.99,
      thumbnails: [
        "https://example.com/images/kh003_front.jpg",
        "https://example.com/images/kh003_back.jpg"
      ],
      brand: BrandModel(id: "brand3", name: "Brand C"),
      description: "A warm and cozy hoodie for kids.",
      productType: "variable",
      categoryId: "cat3",
      categories: ["Kids", "Hoodies"],
      tag: "sale",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["XS", "S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["Pink", "Grey"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "3-1",
            sku: "KH003-P-XS",
            image: "https://example.com/images/kh003_pink_xs.jpg",
            description: "Pink, Extra Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 20,
            attributeValues: {"Size": "XS", "Color": "Pink"}),
        ProductVariationModel(
            id: "3-3",
            sku: "KH003-P-XS",
            image: "https://example.com/images/kh003_pink_xs.jpg",
            description: "Pink, large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Pink"}),
        ProductVariationModel(
            id: "3-2",
            sku: "KH003-G-S",
            image: "https://example.com/images/kh003_grey_s.jpg",
            description: "Grey, Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Grey"}),
      ],
    ),

    // Women's Shoes
    ProductModel(
      id: "4",
      stock: 200,
      sku: "WS004",
      price: 60.99,
      title: "Women's Running Shoes",
      isFeatured: false,
      salePrice: 54.99,
      thumbnails: [
        "https://example.com/images/ws004_front.jpg",
        "https://example.com/images/ws004_side.jpg"
      ],
      brand: BrandModel(id: "brand4", name: "Brand D"),
      description: "Comfortable and stylish running shoes for women.",
      productType: "variable",
      categoryId: "cat4",
      categories: ["Women", "Shoes", "Footwear"],
      tag: "running",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["36", "37", "38", "39"]),
        ProductAttributeModel(name: "Color", values: ["White", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "4-1",
            sku: "WS004-W-6",
            image: "https://example.com/images/ws004_white_6.jpg",
            description: "White, Size 36",
            price: 60.99,
            salePrice: 54.99,
            quantity: 50,
            attributeValues: {"Size": "36", "Color": "White"}),
        ProductVariationModel(
            id: "4-3",
            sku: "WS004-W-9",
            image: "https://example.com/images/ws004_white_6.jpg",
            description: "White, Size 39",
            price: 60.99,
            salePrice: 54.99,
            quantity: 50,
            attributeValues: {"Size": "39", "Color": "White"}),
        ProductVariationModel(
            id: "4-4",
            sku: "WS004-B-9",
            image: "https://example.com/images/ws004_white_6.jpg",
            description: "Black, Size 39",
            price: 60.99,
            salePrice: 54.99,
            quantity: 50,
            attributeValues: {"Size": "39", "Color": "Black"}),
        ProductVariationModel(
            id: "4-2",
            sku: "WS004-B-8",
            image: "https://example.com/images/ws004_black_8.jpg",
            description: "Black, Size 38",
            price: 60.99,
            salePrice: 54.99,
            quantity: 50,
            attributeValues: {"Size": "38", "Color": "Black"}),
      ],
    ),

    // Men's Shoes
    ProductModel(
      id: "5",
      stock: 150,
      sku: "MS005",
      price: 70.99,
      title: "Men's Leather Shoes",
      isFeatured: true,
      salePrice: 65.99,
      thumbnails: [
        "https://example.com/images/ms005_front.jpg",
        "https://example.com/images/ms005_side.jpg"
      ],
      brand: BrandModel(id: "brand5", name: "Brand E"),
      description: "Elegant and durable leather shoes for men.",
      productType: "variable",
      categoryId: "cat5",
      categories: ["Men", "Shoes", "Footwear"],
      tag: "leather",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["8", "9", "10", "11"]),
        ProductAttributeModel(name: "Color", values: ["Brown", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "5-1",
            sku: "MS005-BR-8",
            image: "https://example.com/images/ms005_brown_8.jpg",
            description: "Brown, Size 8",
            price: 70.99,
            salePrice: 65.99,
            quantity: 40,
            attributeValues: {"Size": "8", "Color": "Brown"}),
        ProductVariationModel(
            id: "5-2",
            sku: "MS005-BL-10",
            image: "https://example.com/images/ms005_black_10.jpg",
            description: "Black, Size 10",
            price: 70.99,
            salePrice: 65.99,
            quantity: 40,
            attributeValues: {"Size": "10", "Color": "Black"}),
      ],
    ),

    // Women's Crop Tops
    ProductModel(
      id: "6",
      stock: 100,
      sku: "WC006",
      price: 25.99,
      title: "Women's Crop Top",
      isFeatured: true,
      salePrice: 20.99,
      thumbnails: [
        "https://example.com/images/wc006_front.jpg",
        "https://example.com/images/wc006_back.jpg"
      ],
      brand: BrandModel(id: "brand6", name: "Brand F"),
      description: "Stylish crop top for women.",
      productType: "variable",
      categoryId: "cat6",
      categories: ["Women", "Crop Tops", "Tops"],
      tag: "summer",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["White", "Black", "Pink"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "6-1",
            sku: "WC006-W-S",
            image: "https://example.com/images/wc006_white_s.jpg",
            description: "White, Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "White"}),
        ProductVariationModel(
            id: "6-2",
            sku: "WC006-P-M",
            image: "https://example.com/images/wc006_pink_m.jpg",
            description: "Pink, Medium",
            price: 25.99,
            salePrice: 20.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Pink"}),
        ProductVariationModel(
            id: "6-3",
            sku: "WC006-W-L",
            image: "https://example.com/images/wc006_white_s.jpg",
            description: "White, Large",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "White"}),
      ],
    ),

    // Men's Slippers
    ProductModel(
      id: "7",
      stock: 200,
      sku: "MS007",
      price: 15.99,
      title: "Men's Slippers",
      isFeatured: false,
      salePrice: 12.99,
      thumbnails: [
        "https://example.com/images/ms007_front.jpg",
        "https://example.com/images/ms007_side.jpg"
      ],
      brand: BrandModel(id: "brand7", name: "Brand G"),
      description: "Comfortable and casual slippers for men.",
      productType: "variable",
      categoryId: "cat7",
      categories: ["Men", "Slippers", "Footwear"],
      tag: "casual",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["M", "L", "XL"]),
        ProductAttributeModel(name: "Color", values: ["Blue", "Grey"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "7-1",
            sku: "MS007-B-M",
            image: "https://example.com/images/ms007_blue_m.jpg",
            description: "Blue, Medium",
            price: 15.99,
            salePrice: 12.99,
            quantity: 70,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "7-2",
            sku: "MS007-G-L",
            image: "https://example.com/images/ms007_grey_l.jpg",
            description: "Grey, Large",
            price: 15.99,
            salePrice: 12.99,
            quantity: 70,
            attributeValues: {"Size": "L", "Color": "Grey"}),
        ProductVariationModel(
            id: "7-3",
            sku: "MS007-B-XL",
            image: "https://example.com/images/ms007_blue_xl.jpg",
            description: "Blue, Extra Large",
            price: 15.99,
            salePrice: 12.99,
            quantity: 70,
            attributeValues: {"Size": "XL", "Color": "Blue"}),
      ],
    ),

    // Women's Heels
    ProductModel(
      id: "8",
      stock: 50,
      sku: "WH008",
      price: 80.99,
      title: "Women's High Heels",
      isFeatured: true,
      salePrice: 75.99,
      thumbnails: [
        "https://example.com/images/wh008_front.jpg",
        "https://example.com/images/wh008_side.jpg"
      ],
      brand: BrandModel(id: "brand8", name: "Brand H"),
      description: "Elegant high heels for women.",
      productType: "variable",
      categoryId: "cat8",
      categories: ["Women", "Heels", "Footwear"],
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["6", "7", "8"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "8-1",
            sku: "WH008-R-6",
            image: "https://example.com/images/wh008_red_6.jpg",
            description: "Red, Size 6",
            price: 80.99,
            salePrice: 75.99,
            quantity: 20,
            attributeValues: {"Size": "6", "Color": "Red"}),
        ProductVariationModel(
            id: "8-2",
            sku: "WH008-B-8",
            image: "https://example.com/images/wh008_black_8.jpg",
            description: "Black, Size 8",
            price: 80.99,
            salePrice: 75.99,
            quantity: 20,
            attributeValues: {"Size": "8", "Color": "Black"}),
      ],
    ),

    // Kids' Sandals
    ProductModel(
      id: "9",
      stock: 120,
      sku: "KS009",
      price: 22.99,
      title: "Kids' Sandals",
      isFeatured: true,
      salePrice: 18.99,
      thumbnails: [
        "https://example.com/images/ks009_front.jpg",
        "https://example.com/images/ks009_side.jpg"
      ],
      brand: BrandModel(id: "brand9", name: "Brand I"),
      description: "Comfortable and durable sandals for kids.",
      productType: "variable",
      categoryId: "cat9",
      categories: ["Kids", "Sandals", "Footwear"],
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["XS", "S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["Yellow", "Blue"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "9-1",
            sku: "KS009-Y-XS",
            image: "https://example.com/images/ks009_yellow_xs.jpg",
            description: "Yellow, Extra Small",
            price: 22.99,
            salePrice: 18.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Yellow"}),
        ProductVariationModel(
            id: "9-2",
            sku: "KS009-B-S",
            image: "https://example.com/images/ks009_blue_s.jpg",
            description: "Blue, Small",
            price: 22.99,
            salePrice: 18.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        // Additional Variations
        ProductVariationModel(
            id: "9-3",
            sku: "KS009-Y-S",
            image: "https://example.com/images/ks009_yellow_s.jpg",
            description: "Yellow, Small",
            price: 22.99,
            salePrice: 18.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Yellow"}),
        ProductVariationModel(
            id: "9-4",
            sku: "KS009-B-XS",
            image: "https://example.com/images/ks009_blue_xs.jpg",
            description: "Blue, Extra Small",
            price: 22.99,
            salePrice: 18.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Blue"}),
      ],
    ),

    // Men's Jackets
    ProductModel(
      id: "10",
      stock: 60,
      sku: "MJ010",
      price: 120.99,
      title: "Men's Leather Jacket",
      isFeatured: true,
      salePrice: 110.99,
      thumbnails: [
        "https://example.com/images/mj010_front.jpg",
        "https://example.com/images/mj010_back.jpg"
      ],
      brand: BrandModel(id: "brand10", name: "Brand J"),
      description: "Stylish leather jacket for men.",
      productType: "variable",
      categoryId: "cat10",
      categories: ["Men", "Jackets", "Clothing"],
      tag: "winter",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["M", "L", "XL"]),
        ProductAttributeModel(name: "Color", values: ["Brown", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "10-1",
            sku: "MJ010-BR-M",
            image: "https://example.com/images/mj010_brown_m.jpg",
            description: "Brown, Medium",
            price: 120.99,
            salePrice: 110.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Brown"}),
        ProductVariationModel(
            id: "10-2",
            sku: "MJ010-BR-L",
            image: "https://example.com/images/mj010_brown_l.jpg",
            description: "Brown, Large",
            price: 120.99,
            salePrice: 110.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Brown"}),
        ProductVariationModel(
            id: "10-3",
            sku: "MJ010-BR-XL",
            image: "https://example.com/images/mj010_brown_xl.jpg",
            description: "Brown, Extra Large",
            price: 120.99,
            salePrice: 110.99,
            quantity: 20,
            attributeValues: {"Size": "XL", "Color": "Brown"}),
        ProductVariationModel(
            id: "10-4",
            sku: "MJ010-B-M",
            image: "https://example.com/images/mj010_black_m.jpg",
            description: "Black, Medium",
            price: 120.99,
            salePrice: 110.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "10-5",
            sku: "MJ010-B-L",
            image: "https://example.com/images/mj010_black_l.jpg",
            description: "Black, Large",
            price: 120.99,
            salePrice: 110.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Black"}),
        ProductVariationModel(
            id: "10-6",
            sku: "MJ010-B-XL",
            image: "https://example.com/images/mj010_black_xl.jpg",
            description: "Black, Extra Large",
            price: 120.99,
            salePrice: 110.99,
            quantity: 20,
            attributeValues: {"Size": "XL", "Color": "Black"}),
      ],
    ),

// Women's Blouse
    ProductModel(
      id: "11",
      stock: 100,
      sku: "WB011",
      price: 35.99,
      title: "Women's Casual Blouse",
      isFeatured: true,
      salePrice: 29.99,
      thumbnails: [
        "https://example.com/images/wb011_front.jpg",
        "https://example.com/images/wb011_back.jpg"
      ],
      brand: BrandModel(id: "brand11", name: "Brand K"),
      description: "A stylish and comfortable blouse for everyday wear.",
      productType: "variable",
      categoryId: "cat11",
      categories: ["Women", "Blouses", "Clothing"],
      tag: "new",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L", "XL"]),
        ProductAttributeModel(name: "Color", values: ["White", "Blue", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "11-1",
            sku: "WB011-W-S",
            image: "https://example.com/images/wb011_white_s.jpg",
            description: "White, Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "S", "Color": "White"}),
        ProductVariationModel(
            id: "11-2",
            sku: "WB011-W-M",
            image: "https://example.com/images/wb011_white_m.jpg",
            description: "White, Medium",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "M", "Color": "White"}),
        ProductVariationModel(
            id: "11-3",
            sku: "WB011-W-L",
            image: "https://example.com/images/wb011_white_l.jpg",
            description: "White, Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "L", "Color": "White"}),
        ProductVariationModel(
            id: "11-4",
            sku: "WB011-W-XL",
            image: "https://example.com/images/wb011_white_xl.jpg",
            description: "White, Extra Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "XL", "Color": "White"}),
        ProductVariationModel(
            id: "11-5",
            sku: "WB011-BL-S",
            image: "https://example.com/images/wb011_blue_s.jpg",
            description: "Blue, Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        ProductVariationModel(
            id: "11-6",
            sku: "WB011-BL-M",
            image: "https://example.com/images/wb011_blue_m.jpg",
            description: "Blue, Medium",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "11-7",
            sku: "WB011-BL-L",
            image: "https://example.com/images/wb011_blue_l.jpg",
            description: "Blue, Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "L", "Color": "Blue"}),
        ProductVariationModel(
            id: "11-8",
            sku: "WB011-BL-XL",
            image: "https://example.com/images/wb011_blue_xl.jpg",
            description: "Blue, Extra Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "XL", "Color": "Blue"}),
        ProductVariationModel(
            id: "11-9",
            sku: "WB011-BK-S",
            image: "https://example.com/images/wb011_black_s.jpg",
            description: "Black, Small",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "S", "Color": "Black"}),
        ProductVariationModel(
            id: "11-10",
            sku: "WB011-BK-M",
            image: "https://example.com/images/wb011_black_m.jpg",
            description: "Black, Medium",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "11-11",
            sku: "WB011-BK-L",
            image: "https://example.com/images/wb011_black_l.jpg",
            description: "Black, Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "L", "Color": "Black"}),
        ProductVariationModel(
            id: "11-12",
            sku: "WB011-BK-XL",
            image: "https://example.com/images/wb011_black_xl.jpg",
            description: "Black, Extra Large",
            price: 35.99,
            salePrice: 29.99,
            quantity: 25,
            attributeValues: {"Size": "XL", "Color": "Black"}),
      ],
    ),

    // Men's Shorts
    ProductModel(
      id: "12",
      stock: 80,
      sku: "MS012",
      price: 28.99,
      title: "Men's Cargo Shorts",
      isFeatured: true,
      salePrice: 24.99,
      thumbnails: [
        "https://example.com/images/ms012_front.jpg",
        "https://example.com/images/ms012_back.jpg"
      ],
      brand: BrandModel(id: "brand12", name: "Brand L"),
      description: "Durable and comfortable cargo shorts for men.",
      productType: "variable",
      categoryId: "cat12",
      categories: ["Men", "Shorts", "Clothing"],
      tag: "summer",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["M", "L", "XL"]),
        ProductAttributeModel(name: "Color", values: ["Khaki", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "12-1",
            sku: "MS012-K-M",
            image: "https://example.com/images/ms012_khaki_m.jpg",
            description: "Khaki, Medium",
            price: 28.99,
            salePrice: 24.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Khaki"}),
        ProductVariationModel(
            id: "12-2",
            sku: "MS012-K-L",
            image: "https://example.com/images/ms012_khaki_l.jpg",
            description: "Khaki, Large",
            price: 28.99,
            salePrice: 24.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Khaki"}),
        ProductVariationModel(
            id: "12-3",
            sku: "MS012-K-XL",
            image: "https://example.com/images/ms012_khaki_xl.jpg",
            description: "Khaki, Extra Large",
            price: 28.99,
            salePrice: 24.99,
            quantity: 20,
            attributeValues: {"Size": "XL", "Color": "Khaki"}),
        ProductVariationModel(
            id: "12-4",
            sku: "MS012-B-M",
            image: "https://example.com/images/ms012_black_m.jpg",
            description: "Black, Medium",
            price: 28.99,
            salePrice: 24.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "12-5",
            sku: "MS012-B-L",
            image: "https://example.com/images/ms012_black_l.jpg",
            description: "Black, Large",
            price: 28.99,
            salePrice: 24.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Black"}),
        ProductVariationModel(
            id: "12-6",
            sku: "MS012-B-XL",
            image: "https://example.com/images/ms012_black_xl.jpg",
            description: "Black, Extra Large",
            price: 28.99,
            salePrice: 24.99,
            quantity: 20,
            attributeValues: {"Size": "XL", "Color": "Black"}),
      ],
    ),

    // Kids' T-Shirt
    ProductModel(
      id: "13",
      stock: 150,
      sku: "KT013",
      price: 19.99,
      title: "Kids' Graphic T-Shirt",
      isFeatured: false,
      salePrice: 15.99,
      thumbnails: [
        "https://example.com/images/kt013_front.jpg",
        "https://example.com/images/kt013_back.jpg"
      ],
      brand: BrandModel(id: "brand13", name: "Brand M"),
      description: "Fun and colorful graphic t-shirt for kids.",
      productType: "variable",
      categoryId: "cat13",
      categories: ["Kids", "T-Shirts", "Clothing"],
      tag: "new",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["XS", "S", "M"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Yellow", "Blue"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "13-1",
            sku: "KT013-R-XS",
            image: "https://example.com/images/kt013_red_xs.jpg",
            description: "Red, Extra Small",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Red"}),
        ProductVariationModel(
            id: "13-2",
            sku: "KT013-R-S",
            image: "https://example.com/images/kt013_red_s.jpg",
            description: "Red, Small",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Red"}),
        ProductVariationModel(
            id: "13-3",
            sku: "KT013-R-M",
            image: "https://example.com/images/kt013_red_m.jpg",
            description: "Red, Medium",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Red"}),
        ProductVariationModel(
            id: "13-4",
            sku: "KT013-Y-XS",
            image: "https://example.com/images/kt013_yellow_xs.jpg",
            description: "Yellow, Extra Small",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Yellow"}),
        ProductVariationModel(
            id: "13-5",
            sku: "KT013-Y-S",
            image: "https://example.com/images/kt013_yellow_s.jpg",
            description: "Yellow, Small",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Yellow"}),
        ProductVariationModel(
            id: "13-6",
            sku: "KT013-Y-M",
            image: "https://example.com/images/kt013_yellow_m.jpg",
            description: "Yellow, Medium",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Yellow"}),
        ProductVariationModel(
            id: "13-7",
            sku: "KT013-B-XS",
            image: "https://example.com/images/kt013_blue_xs.jpg",
            description: "Blue, Extra Small",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Blue"}),
        ProductVariationModel(
            id: "13-8",
            sku: "KT013-B-S",
            image: "https://example.com/images/kt013_blue_s.jpg",
            description: "Blue, Small",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        ProductVariationModel(
            id: "13-9",
            sku: "KT013-B-M",
            image: "https://example.com/images/kt013_blue_m.jpg",
            description: "Blue, Medium",
            price: 19.99,
            salePrice: 15.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Blue"}),
      ],
    ),

    // Women's Skirt
    ProductModel(
      id: "14",
      stock: 70,
      sku: "WS014",
      price: 40.99,
      title: "Women's A-line Skirt",
      isFeatured: true,
      salePrice: 35.99,
      thumbnails: [
        "https://example.com/images/ws014_front.jpg",
        "https://example.com/images/ws014_back.jpg"
      ],
      brand: BrandModel(id: "brand14", name: "Brand N"),
      description: "Elegant A-line skirt for women.",
      productType: "variable",
      categoryId: "cat14",
      categories: ["Women", "Skirts", "Clothing"],
      tag: "elegant",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Navy", "Grey"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "14-1",
            sku: "WS014-BK-S",
            image: "https://example.com/images/ws014_black_s.jpg",
            description: "Black, Small",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Black"}),
        ProductVariationModel(
            id: "14-2",
            sku: "WS014-BK-M",
            image: "https://example.com/images/ws014_black_m.jpg",
            description: "Black, Medium",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "14-3",
            sku: "WS014-BK-L",
            image: "https://example.com/images/ws014_black_l.jpg",
            description: "Black, Large",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Black"}),
        ProductVariationModel(
            id: "14-4",
            sku: "WS014-N-S",
            image: "https://example.com/images/ws014_navy_s.jpg",
            description: "Navy, Small",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Navy"}),
        ProductVariationModel(
            id: "14-5",
            sku: "WS014-N-M",
            image: "https://example.com/images/ws014_navy_m.jpg",
            description: "Navy, Medium",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Navy"}),
        ProductVariationModel(
            id: "14-6",
            sku: "WS014-N-L",
            image: "https://example.com/images/ws014_navy_l.jpg",
            description: "Navy, Large",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Navy"}),
        ProductVariationModel(
            id: "14-7",
            sku: "WS014-G-S",
            image: "https://example.com/images/ws014_grey_s.jpg",
            description: "Grey, Small",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Grey"}),
        ProductVariationModel(
            id: "14-8",
            sku: "WS014-G-M",
            image: "https://example.com/images/ws014_grey_m.jpg",
            description: "Grey, Medium",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Grey"}),
        ProductVariationModel(
            id: "14-9",
            sku: "WS014-G-L",
            image: "https://example.com/images/ws014_grey_l.jpg",
            description: "Grey, Large",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Grey"}),
      ],
    ),

    // Men's Hats
    ProductModel(
      id: "15",
      stock: 100,
      sku: "MH015",
      price: 15.99,
      title: "Men's Baseball Cap",
      isFeatured: false,
      salePrice: 12.99,
      thumbnails: [
        "https://example.com/images/mh015_front.jpg",
        "https://example.com/images/mh015_side.jpg"
      ],
      brand: BrandModel(id: "brand15", name: "Brand O"),
      description: "Classic baseball cap for men.",
      productType: "variable",
      categoryId: "cat15",
      categories: ["Men", "Hats", "Accessories"],
      tag: "casual",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["M"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Black", "White"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "15-1",
            sku: "MH015-R-M",
            image: "https://example.com/images/mh015_red_os.jpg",
            description: "Red, M",
            price: 15.99,
            salePrice: 12.99,
            quantity: 40,
            attributeValues: {"Size": "M", "Color": "Red"}),
        ProductVariationModel(
            id: "15-2",
            sku: "MH015-BK-M",
            image: "https://example.com/images/mh015_black_os.jpg",
            description: "Black, M",
            price: 15.99,
            salePrice: 12.99,
            quantity: 40,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "15-3",
            sku: "MH015-W-M",
            image: "https://example.com/images/mh015_white_os.jpg",
            description: "White, M",
            price: 15.99,
            salePrice: 12.99,
            quantity: 40,
            attributeValues: {"Size": "M", "Color": "White"}),
      ],
    ),

    // Women's Handbag
    ProductModel(
      id: "16",
      stock: 50,
      sku: "WH016",
      price: 60.99,
      title: "Women's Leather Handbag",
      isFeatured: true,
      salePrice: 55.99,
      thumbnails: [
        "https://example.com/images/wh016_front.jpg",
        "https://example.com/images/wh016_side.jpg"
      ],
      brand: BrandModel(id: "brand16", name: "Brand P"),
      description: "Elegant leather handbag for women.",
      productType: "variable",
      categoryId: "cat16",
      categories: ["Women", "Handbags", "Accessories"],
      tag: "fashion",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["M"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Brown"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "16-1",
            sku: "WH016-BK-M",
            image: "https://example.com/images/wh016_black_os.jpg",
            description: "Black, M",
            price: 60.99,
            salePrice: 55.99,
            quantity: 25,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "16-2",
            sku: "WH016-BR-M",
            image: "https://example.com/images/wh016_brown_os.jpg",
            description: "Brown, M",
            price: 60.99,
            salePrice: 55.99,
            quantity: 25,
            attributeValues: {"Size": "M", "Color": "Brown"}),
      ],
    ),

    // Kids' Backpack
    ProductModel(
      id: "17",
      stock: 80,
      sku: "KB017",
      price: 25.99,
      title: "Kids' School Backpack",
      isFeatured: true,
      salePrice: 20.99,
      thumbnails: [
        "https://example.com/images/kb017_front.jpg",
        "https://example.com/images/kb017_side.jpg"
      ],
      brand: BrandModel(id: "brand17", name: "Brand Q"),
      description: "Durable and colorful backpack for kids.",
      productType: "variable",
      categoryId: "cat17",
      categories: ["Kids", "Bag", "Backpack", "Accessories"],
      tag: "school",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Blue", "Green"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "17-1",
            sku: "KB017-R-OS",
            image: "https://example.com/images/kb017_red_os.jpg",
            description: "Red, One Size",
            price: 25.99,
            salePrice: 20.99,
            quantity: 30,
            attributeValues: {"Size": "One Size", "Color": "Red"}),
        ProductVariationModel(
            id: "17-2",
            sku: "KB017-B-OS",
            image: "https://example.com/images/kb017_blue_os.jpg",
            description: "Blue, One Size",
            price: 25.99,
            salePrice: 20.99,
            quantity: 30,
            attributeValues: {"Size": "One Size", "Color": "Blue"}),
        ProductVariationModel(
            id: "17-3",
            sku: "KB017-G-OS",
            image: "https://example.com/images/kb017_green_os.jpg",
            description: "Green, One Size",
            price: 25.99,
            salePrice: 20.99,
            quantity: 30,
            attributeValues: {"Size": "One Size", "Color": "Green"}),
      ],
    ),

    // Men's Boots
    ProductModel(
      id: "18",
      stock: 60,
      sku: "MB018",
      price: 95.99,
      title: "Men's Leather Boots",
      isFeatured: true,
      salePrice: 89.99,
      thumbnails: [
        "https://example.com/images/mb018_front.jpg",
        "https://example.com/images/mb018_side.jpg"
      ],
      brand: BrandModel(id: "brand18", name: "Brand R"),
      description: "Rugged leather boots for men.",
      productType: "variable",
      categoryId: "cat18",
      categories: ["Men", "Boots", "Shoes", "Footwear"],
      tag: "winter",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["9", "10", "11"]),
        ProductAttributeModel(name: "Color", values: ["Brown", "Black"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "18-1",
            sku: "MB018-BR-9",
            image: "https://example.com/images/mb018_brown_9.jpg",
            description: "Brown, Size 9",
            price: 95.99,
            salePrice: 89.99,
            quantity: 20,
            attributeValues: {"Size": "9", "Color": "Brown"}),
        ProductVariationModel(
            id: "18-2",
            sku: "MB018-BR-10",
            image: "https://example.com/images/mb018_brown_10.jpg",
            description: "Brown, Size 10",
            price: 95.99,
            salePrice: 89.99,
            quantity: 20,
            attributeValues: {"Size": "10", "Color": "Brown"}),
        ProductVariationModel(
            id: "18-3",
            sku: "MB018-BR-11",
            image: "https://example.com/images/mb018_brown_11.jpg",
            description: "Brown, Size 11",
            price: 95.99,
            salePrice: 89.99,
            quantity: 20,
            attributeValues: {"Size": "11", "Color": "Brown"}),
        ProductVariationModel(
            id: "18-4",
            sku: "MB018-B-9",
            image: "https://example.com/images/mb018_black_9.jpg",
            description: "Black, Size 9",
            price: 95.99,
            salePrice: 89.99,
            quantity: 20,
            attributeValues: {"Size": "9", "Color": "Black"}),
        ProductVariationModel(
            id: "18-5",
            sku: "MB018-B-10",
            image: "https://example.com/images/mb018_black_10.jpg",
            description: "Black, Size 10",
            price: 95.99,
            salePrice: 89.99,
            quantity: 20,
            attributeValues: {"Size": "10", "Color": "Black"}),
        ProductVariationModel(
            id: "18-6",
            sku: "MB018-B-11",
            image: "https://example.com/images/mb018_black_11.jpg",
            description: "Black, Size 11",
            price: 95.99,
            salePrice: 89.99,
            quantity: 20,
            attributeValues: {"Size": "11", "Color": "Black"}),
      ],
    ),

    // Women's Sandals
    ProductModel(
      id: "19",
      stock: 80,
      sku: "WS019",
      price: 40.99,
      title: "Women's Beach Sandals",
      isFeatured: true,
      salePrice: 35.99,
      thumbnails: [
        "https://example.com/images/ws019_front.jpg",
        "https://example.com/images/ws019_side.jpg"
      ],
      brand: BrandModel(id: "brand19", name: "Brand S"),
      description: "Comfortable and stylish sandals for the beach.",
      productType: "variable",
      categoryId: "cat19",
      categories: ["Women", "Sandals", "Footwear"],
      tag: "summer",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["6", "7", "8"]),
        ProductAttributeModel(name: "Color", values: ["White", "Blue", "Pink"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "19-1",
            sku: "WS019-W-6",
            image: "https://example.com/images/ws019_white_6.jpg",
            description: "White, Size 6",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "6", "Color": "White"}),
        ProductVariationModel(
            id: "19-2",
            sku: "WS019-W-7",
            image: "https://example.com/images/ws019_white_7.jpg",
            description: "White, Size 7",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "7", "Color": "White"}),
        ProductVariationModel(
            id: "19-3",
            sku: "WS019-W-8",
            image: "https://example.com/images/ws019_white_8.jpg",
            description: "White, Size 8",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "8", "Color": "White"}),
        ProductVariationModel(
            id: "19-4",
            sku: "WS019-B-6",
            image: "https://example.com/images/ws019_blue_6.jpg",
            description: "Blue, Size 6",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "6", "Color": "Blue"}),
        ProductVariationModel(
            id: "19-5",
            sku: "WS019-B-7",
            image: "https://example.com/images/ws019_blue_7.jpg",
            description: "Blue, Size 7",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "7", "Color": "Blue"}),
        ProductVariationModel(
            id: "19-6",
            sku: "WS019-B-8",
            image: "https://example.com/images/ws019_blue_8.jpg",
            description: "Blue, Size 8",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "8", "Color": "Blue"}),
        ProductVariationModel(
            id: "19-7",
            sku: "WS019-P-6",
            image: "https://example.com/images/ws019_pink_6.jpg",
            description: "Pink, Size 6",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "6", "Color": "Pink"}),
        ProductVariationModel(
            id: "19-8",
            sku: "WS019-P-7",
            image: "https://example.com/images/ws019_pink_7.jpg",
            description: "Pink, Size 7",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "7", "Color": "Pink"}),
        ProductVariationModel(
            id: "19-9",
            sku: "WS019-P-8",
            image: "https://example.com/images/ws019_pink_8.jpg",
            description: "Pink, Size 8",
            price: 40.99,
            salePrice: 35.99,
            quantity: 20,
            attributeValues: {"Size": "8", "Color": "Pink"}),
      ],
    ),

    // Kids' Hoodie
    ProductModel(
      id: "20",
      stock: 90,
      sku: "KH020",
      price: 30.99,
      title: "Kids' Hoodie",
      isFeatured: false,
      salePrice: 25.99,
      thumbnails: [
        "https://example.com/images/kh020_front.jpg",
        "https://example.com/images/kh020_back.jpg"
      ],
      brand: BrandModel(id: "brand20", name: "Brand T"),
      description: "Warm and cozy hoodie for kids.",
      productType: "variable",
      categoryId: "cat20",
      categories: ["Kids", "Hoodies", "Clothing"],
      tag: "winter",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["XS", "S", "M"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Blue", "Green"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "20-1",
            sku: "KH020-R-XS",
            image: "https://example.com/images/kh020_red_xs.jpg",
            description: "Red, Extra Small",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Red"}),
        ProductVariationModel(
            id: "20-2",
            sku: "KH020-R-S",
            image: "https://example.com/images/kh020_red_s.jpg",
            description: "Red, Small",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Red"}),
        ProductVariationModel(
            id: "20-3",
            sku: "KH020-R-M",
            image: "https://example.com/images/kh020_red_m.jpg",
            description: "Red, Medium",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Red"}),
        ProductVariationModel(
            id: "20-4",
            sku: "KH020-B-XS",
            image: "https://example.com/images/kh020_blue_xs.jpg",
            description: "Blue, Extra Small",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Blue"}),
        ProductVariationModel(
            id: "20-5",
            sku: "KH020-B-S",
            image: "https://example.com/images/kh020_blue_s.jpg",
            description: "Blue, Small",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        ProductVariationModel(
            id: "20-6",
            sku: "KH020-B-M",
            image: "https://example.com/images/kh020_blue_m.jpg",
            description: "Blue, Medium",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "20-7",
            sku: "KH020-G-XS",
            image: "https://example.com/images/kh020_green_xs.jpg",
            description: "Green, Extra Small",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "XS", "Color": "Green"}),
        ProductVariationModel(
            id: "20-8",
            sku: "KH020-G-S",
            image: "https://example.com/images/kh020_green_s.jpg",
            description: "Green, Small",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "S", "Color": "Green"}),
        ProductVariationModel(
            id: "20-9",
            sku: "KH020-G-M",
            image: "https://example.com/images/kh020_green_m.jpg",
            description: "Green, Medium",
            price: 30.99,
            salePrice: 25.99,
            quantity: 30,
            attributeValues: {"Size": "M", "Color": "Green"}),
      ],
    ),

    // Women's Scarf
    ProductModel(
      id: "21",
      stock: 60,
      sku: "WS021",
      price: 18.99,
      title: "Women's Silk Scarf",
      isFeatured: false,
      salePrice: 15.99,
      thumbnails: [
        "https://example.com/images/ws021_front.jpg",
        "https://example.com/images/ws021_side.jpg"
      ],
      brand: BrandModel(id: "brand21", name: "Brand U"),
      description: "Elegant and soft silk scarf for women.",
      productType: "variable",
      categoryId: "cat21",
      categories: ["Women", "Scarves", "Accessories"],
      tag: "fashion",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Black", "White"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "21-1",
            sku: "WS021-R-OS",
            image: "https://example.com/images/ws021_red_os.jpg",
            description: "Red, One Size",
            price: 18.99,
            salePrice: 15.99,
            quantity: 20,
            attributeValues: {"Size": "One Size", "Color": "Red"}),
        ProductVariationModel(
            id: "21-2",
            sku: "WS021-B-OS",
            image: "https://example.com/images/ws021_black_os.jpg",
            description: "Black, One Size",
            price: 18.99,
            salePrice: 15.99,
            quantity: 20,
            attributeValues: {"Size": "One Size", "Color": "Black"}),
        ProductVariationModel(
            id: "21-3",
            sku: "WS021-W-OS",
            image: "https://example.com/images/ws021_white_os.jpg",
            description: "White, One Size",
            price: 18.99,
            salePrice: 15.99,
            quantity: 20,
            attributeValues: {"Size": "One Size", "Color": "White"}),
      ],
    ),

    // Men's Watch
    ProductModel(
      id: "22",
      stock: 50,
      sku: "MW022",
      price: 120.99,
      title: "Men's Sports Watch",
      isFeatured: true,
      salePrice: 110.99,
      thumbnails: [
        "https://example.com/images/mw022_front.jpg",
        "https://example.com/images/mw022_side.jpg"
      ],
      brand: BrandModel(id: "brand22", name: "Brand V"),
      description: "Durable and stylish sports watch for men.",
      productType: "variable",
      categoryId: "cat22",
      categories: ["Men", "Watches", "Accessories"],
      tag: "sport",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Silver"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "22-1",
            sku: "MW022-B-OS",
            image: "https://example.com/images/mw022_black_os.jpg",
            description: "Black, One Size",
            price: 120.99,
            salePrice: 110.99,
            quantity: 25,
            attributeValues: {"Size": "One Size", "Color": "Black"}),
        ProductVariationModel(
            id: "22-2",
            sku: "MW022-S-OS",
            image: "https://example.com/images/mw022_silver_os.jpg",
            description: "Silver, One Size",
            price: 120.99,
            salePrice: 110.99,
            quantity: 25,
            attributeValues: {"Size": "One Size", "Color": "Silver"}),
      ],
    ),

    // Women's Sunglasses
    ProductModel(
      id: "23",
      stock: 70,
      sku: "WS023",
      price: 35.99,
      title: "Women's Designer Sunglasses",
      isFeatured: true,
      salePrice: 30.99,
      thumbnails: [
        "https://example.com/images/ws023_front.jpg",
        "https://example.com/images/ws023_side.jpg"
      ],
      brand: BrandModel(id: "brand23", name: "Brand W"),
      description: "Chic and stylish sunglasses for women.",
      productType: "variable",
      categoryId: "cat23",
      categories: ["Women", "Sunglasses", "Accessories"],
      tag: "fashion",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Brown"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "23-1",
            sku: "WS023-BK-OS",
            image: "https://example.com/images/ws023_black_os.jpg",
            description: "Black, One Size",
            price: 35.99,
            salePrice: 30.99,
            quantity: 35,
            attributeValues: {"Size": "One Size", "Color": "Black"}),
        ProductVariationModel(
            id: "23-2",
            sku: "WS023-BR-OS",
            image: "https://example.com/images/ws023_brown_os.jpg",
            description: "Brown, One Size",
            price: 35.99,
            salePrice: 30.99,
            quantity: 35,
            attributeValues: {"Size": "One Size", "Color": "Brown"}),
      ],
    ),

    // Men's Wallet
    ProductModel(
      id: "24",
      stock: 80,
      sku: "MW024",
      price: 45.99,
      title: "Men's Leather Wallet",
      isFeatured: true,
      salePrice: 40.99,
      thumbnails: [
        "https://example.com/images/mw024_front.jpg",
        "https://example.com/images/mw024_side.jpg"
      ],
      brand: BrandModel(id: "brand24", name: "Brand X"),
      description: "Elegant leather wallet for men.",
      productType: "variable",
      categoryId: "cat24",
      categories: ["Men", "Wallets", "Accessories"],
      tag: "fashion",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Brown"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "24-1",
            sku: "MW024-BK-OS",
            image: "https://example.com/images/mw024_black_os.jpg",
            description: "Black, One Size",
            price: 45.99,
            salePrice: 40.99,
            quantity: 40,
            attributeValues: {"Size": "One Size", "Color": "Black"}),
        ProductVariationModel(
            id: "24-2",
            sku: "MW024-BR-OS",
            image: "https://example.com/images/mw024_brown_os.jpg",
            description: "Brown, One Size",
            price: 45.99,
            salePrice: 40.99,
            quantity: 40,
            attributeValues: {"Size": "One Size", "Color": "Brown"}),
      ],
    ),

    // Kids' Sneakers
    ProductModel(
      id: "25",
      stock: 90,
      sku: "KS025",
      price: 55.99,
      title: "Kids' Light-Up Sneakers",
      isFeatured: true,
      salePrice: 50.99,
      thumbnails: [
        "https://example.com/images/ks025_front.jpg",
        "https://example.com/images/ks025_side.jpg"
      ],
      brand: BrandModel(id: "brand25", name: "Brand Y"),
      description: "Fun and colorful light-up sneakers for kids.",
      productType: "variable",
      categoryId: "cat25",
      categories: ["Kids", "Sneakers", "Footwear"],
      tag: "new",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["8", "9", "10"]),
        ProductAttributeModel(name: "Color", values: ["Red", "Blue", "Green"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "25-1",
            sku: "KS025-R-8",
            image: "https://example.com/images/ks025_red_8.jpg",
            description: "Red, Size 8",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "8", "Color": "Red"}),
        ProductVariationModel(
            id: "25-2",
            sku: "KS025-R-9",
            image: "https://example.com/images/ks025_red_9.jpg",
            description: "Red, Size 9",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "9", "Color": "Red"}),
        ProductVariationModel(
            id: "25-3",
            sku: "KS025-R-10",
            image: "https://example.com/images/ks025_red_10.jpg",
            description: "Red, Size 10",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "10", "Color": "Red"}),
        ProductVariationModel(
            id: "25-4",
            sku: "KS025-B-8",
            image: "https://example.com/images/ks025_blue_8.jpg",
            description: "Blue, Size 8",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "8", "Color": "Blue"}),
        ProductVariationModel(
            id: "25-5",
            sku: "KS025-B-9",
            image: "https://example.com/images/ks025_blue_9.jpg",
            description: "Blue, Size 9",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "9", "Color": "Blue"}),
        ProductVariationModel(
            id: "25-6",
            sku: "KS025-B-10",
            image: "https://example.com/images/ks025_blue_10.jpg",
            description: "Blue, Size 10",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "10", "Color": "Blue"}),
        ProductVariationModel(
            id: "25-7",
            sku: "KS025-G-8",
            image: "https://example.com/images/ks025_green_8.jpg",
            description: "Green, Size 8",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "8", "Color": "Green"}),
        ProductVariationModel(
            id: "25-8",
            sku: "KS025-G-9",
            image: "https://example.com/images/ks025_green_9.jpg",
            description: "Green, Size 9",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "9", "Color": "Green"}),
        ProductVariationModel(
            id: "25-9",
            sku: "KS025-G-10",
            image: "https://example.com/images/ks025_green_10.jpg",
            description: "Green, Size 10",
            price: 55.99,
            salePrice: 50.99,
            quantity: 30,
            attributeValues: {"Size": "10", "Color": "Green"}),
      ],
    ),

    // Women's Swimsuit
    ProductModel(
      id: "26",
      stock: 60,
      sku: "WS026",
      price: 70.99,
      title: "Women's One-Piece Swimsuit",
      isFeatured: true,
      salePrice: 65.99,
      thumbnails: [
        "https://example.com/images/ws026_front.jpg",
        "https://example.com/images/ws026_back.jpg"
      ],
      brand: BrandModel(id: "brand26", name: "Brand Z"),
      description: "Stylish and comfortable one-piece swimsuit for women.",
      productType: "Variable",
      categoryId: "cat26",
      categories: ["Women", "Swimwear", "Clothing"],
      tag: "summer",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["S", "M", "L"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Blue", "Red"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "26-1",
            sku: "WS026-BK-S",
            image: "https://example.com/images/ws026_black_s.jpg",
            description: "Black, Small",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Black"}),
        ProductVariationModel(
            id: "26-2",
            sku: "WS026-B-M",
            image: "https://example.com/images/ws026_blue_m.jpg",
            description: "Blue, Medium",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "26-3",
            sku: "WS026-BK-S",
            image: "https://example.com/images/ws026_black_s.jpg",
            description: "Black, Small",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Black"}),
        ProductVariationModel(
            id: "26-4",
            sku: "WS026-BL-S",
            image: "https://example.com/images/ws026_blue_s.jpg",
            description: "Blue, Small",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        ProductVariationModel(
            id: "26-5",
            sku: "WS026-R-S",
            image: "https://example.com/images/ws026_red_s.jpg",
            description: "Red, Small",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Red"}),
        ProductVariationModel(
            id: "26-6",
            sku: "WS026-BK-M",
            image: "https://example.com/images/ws026_black_m.jpg",
            description: "Black, Medium",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Black"}),
        ProductVariationModel(
            id: "26-7",
            sku: "WS026-BL-M",
            image: "https://example.com/images/ws026_blue_m.jpg",
            description: "Blue, Medium",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "26-8",
            sku: "WS026-R-M",
            image: "https://example.com/images/ws026_red_m.jpg",
            description: "Red, Medium",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Red"}),
        ProductVariationModel(
            id: "26-9",
            sku: "WS026-BK-L",
            image: "https://example.com/images/ws026_black_l.jpg",
            description: "Black, Large",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Black"}),
        ProductVariationModel(
            id: "26-10",
            sku: "WS026-BL-L",
            image: "https://example.com/images/ws026_blue_l.jpg",
            description: "Blue, Large",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Blue"}),
        ProductVariationModel(
            id: "26-11",
            sku: "WS026-R-L",
            image: "https://example.com/images/ws026_red_l.jpg",
            description: "Red, Large",
            price: 70.99,
            salePrice: 65.99,
            quantity: 20,
            attributeValues: {"Size": "L", "Color": "Red"}),
      ],
    ),

    // Men's Beanie
    ProductModel(
      id: "28",
      stock: 70,
      sku: "MB028",
      price: 15.99,
      title: "Men's Winter Beanie",
      isFeatured: false,
      salePrice: 12.99,
      thumbnails: [
        "https://example.com/images/mb028_front.jpg",
        "https://example.com/images/mb028_side.jpg"
      ],
      brand: BrandModel(id: "brand28", name: "Brand BB"),
      description: "Warm and stylish winter beanie for men.",
      productType: "Variable",
      categoryId: "cat28",
      categories: ["Men", "Hats", "Accessories"],
      tag: "winter",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Black", "Grey"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "28-1",
            sku: "MB028-BK-OS",
            image: "https://example.com/images/mb028_black_os.jpg",
            description: "Black, One Size",
            price: 15.99,
            salePrice: 12.99,
            quantity: 35,
            attributeValues: {"Size": "One Size", "Color": "Black"}),
        ProductVariationModel(
            id: "28-2",
            sku: "MB028-G-OS",
            image: "https://example.com/images/mb028_grey_os.jpg",
            description: "Grey, One Size",
            price: 15.99,
            salePrice: 12.99,
            quantity: 35,
            attributeValues: {"Size": "One Size", "Color": "Grey"}),
      ],
    ),

    // Women's Bracelet
    ProductModel(
      id: "29",
      stock: 40,
      sku: "WB029",
      price: 45.99,
      title: "Women's Gold Bracelet",
      isFeatured: true,
      salePrice: 39.99,
      thumbnails: [
        "https://example.com/images/wb029_front.jpg",
        "https://example.com/images/wb029_side.jpg"
      ],
      brand: BrandModel(id: "brand29", name: "Brand CC"),
      description: "Elegant and stylish gold bracelet for women.",
      productType: "single",
      categoryId: "cat29",
      categories: ["Women", "Jewelry", "Accessories"],
      tag: "luxury",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["One Size"]),
        ProductAttributeModel(name: "Color", values: ["Gold"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "29-1",
            sku: "WB029-G-OS",
            image: "https://example.com/images/wb029_gold_os.jpg",
            description: "Gold, One Size",
            price: 45.99,
            salePrice: 39.99,
            quantity: 40,
            attributeValues: {"Size": "One Size", "Color": "Gold"}),
      ],
    ),

    // Kids' Pajamas
    ProductModel(
      id: "30",
      stock: 50,
      sku: "KP030",
      price: 25.99,
      title: "Kids' Pajama Set",
      isFeatured: false,
      salePrice: 20.99,
      thumbnails: [
        "https://example.com/images/kp030_front.jpg",
        "https://example.com/images/kp030_back.jpg"
      ],
      brand: BrandModel(id: "brand30", name: "Brand DD"),
      description: "Comfortable and cozy pajama set for kids.",
      productType: "Variable",
      categoryId: "cat30",
      categories: ["Kids", "Sleepwear", "Clothing"],
      tag: "winter",
      productAttribute: [
        ProductAttributeModel(name: "Size", values: ["XS", "S", "M"]),
        ProductAttributeModel(name: "Color", values: ["Pink", "Blue", "Green"])
      ],
      productVariation: [
        ProductVariationModel(
            id: "30-1",
            sku: "KP030-P-XS",
            image: "https://example.com/images/kp030_pink_xs.jpg",
            description: "Pink, Extra Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "XS", "Color": "Pink"}),
        ProductVariationModel(
            id: "30-2",
            sku: "KP030-B-S",
            image: "https://example.com/images/kp030_blue_s.jpg",
            description: "Blue, Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Blue"}),
        ProductVariationModel(
            id: "30-4",
            sku: "KP030-B-XS",
            image: "https://example.com/images/kp030_blue_xs.jpg",
            description: "Blue, Extra Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "XS", "Color": "Blue"}),
        ProductVariationModel(
            id: "30-5",
            sku: "KP030-G-XS",
            image: "https://example.com/images/kp030_green_xs.jpg",
            description: "Green, Extra Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "XS", "Color": "Green"}),
        ProductVariationModel(
            id: "30-6",
            sku: "KP030-P-S",
            image: "https://example.com/images/kp030_pink_s.jpg",
            description: "Pink, Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Pink"}),
        ProductVariationModel(
            id: "30-8",
            sku: "KP030-G-S",
            image: "https://example.com/images/kp030_green_s.jpg",
            description: "Green, Small",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "S", "Color": "Green"}),
        ProductVariationModel(
            id: "30-9",
            sku: "KP030-P-M",
            image: "https://example.com/images/kp030_pink_m.jpg",
            description: "Pink, Medium",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Pink"}),
        ProductVariationModel(
            id: "30-10",
            sku: "KP030-B-M",
            image: "https://example.com/images/kp030_blue_m.jpg",
            description: "Blue, Medium",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Blue"}),
        ProductVariationModel(
            id: "30-11",
            sku: "KP030-G-M",
            image: "https://example.com/images/kp030_green_m.jpg",
            description: "Green, Medium",
            price: 25.99,
            salePrice: 20.99,
            quantity: 20,
            attributeValues: {"Size": "M", "Color": "Green"}),
      ],
    ),
  ];
}
